server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${DB_POSTGRESDB_USER}
spring.datasource.password=${DB_POSTGRESDB_PASSWORD}
spring.sql.init.platform=${DB_TYPE}
spring.jpa.hibernate.ddl-auto=create
logging.level.org.springframework.security=DEBUG
spring.servlet.multipart.max-file-size=1000MB
spring.jpa.open-in-view=true

#Redis
spring.data.redis.url=${REDIS_URL}
spring.data.redis.ssl.enabled=true
spring.cache.type=redis

#Swagger
app.server.url=${SWAGGER_URL}

#Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Email
spring.mail.username=${EMAIL}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.from=${EMAIL_SENDER}
spring.mail.protocol=smtp
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.from=${EMAIL_SENDER}
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
